import type { Metadata } from "next";
import "./globals.css";

import { inter } from "./ui/fonts";


export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${inter}`}
      >
        {children}
      </body>
    </html>
  );
}
